#!/bin/bash 

# create script
# Author Paresh

#Is tehre an argument
if [[ ! $1 ]]; then
	echo "Missing argument" 
	exit 1
fi

scriptname="$1"
bindir="${HOME}/bin"
filename="${bindir}/${scriptname}"

if [[ -e $filename ]]; then
	echo "File ${filename} already exists"
	exit 1
fi

if type "$scriptname" > /dev/null 2>&1; then
	echo "There is already a command with name ${scriptname}"
	exit 1
fi

#check bin directory exist
if [[ ! -d $bindir ]]; then
	#if not : create bin directory
	if mkdir "$bindir"; then
		echo "Created ${bindir}"
	else
		echo "Cound not create ${bindir}. "
		exit 1
	fi
fi

#create a script with a single line
echo '#!/bin/bash' > "$filename"
# Add executable permission
chmod u+x "$filename"
# Open with editor
if [[ $EDITOR ]]; then
	$EDITOR "$filename"
else
	echo "Script created; not starting editor because \$EDITOR is not set."
fi



