#!/bin/bash

# Change filename extensions

# if [[ $# -ne 2 ]]; then
#	echo "Need exactly two arguments" >&2
# fi

[[ $# -ne 2 ]] && { echo "Need exactly two arguments" >&2; exit 1; }

for f in *"$1"; do
#	base=$(basename "$f" "$1")
#	mv "$f" "${base}$2"
	mv -- "$f" "${f/%$1/$2}"
done

